# Generated by Django 4.1 on 2024-02-10 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_combinedtestcategory_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='title',
            new_name='name',
        ),
    ]
