# Generated by Django 4.1 on 2024-02-16 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_tests', '0006_remove_grouptest_easy_test_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='easyquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='easy_question', to='group_tests.grouptest'),
        ),
        migrations.AlterField(
            model_name='hardquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hards_question', to='group_tests.grouptest'),
        ),
        migrations.AlterField(
            model_name='mediumquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='madium_question', to='group_tests.grouptest'),
        ),
    ]
