# Generated by Django 4.1 on 2024-02-17 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_tests', '0007_alter_easyquestion_test_alter_hardquestion_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hard_question', to='group_tests.grouptest'),
        ),
        migrations.AlterField(
            model_name='mediumquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medium_question', to='group_tests.grouptest'),
        ),
    ]
