# Generated by Django 4.1 on 2024-02-21 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_tests', '0012_categorytestsessionscoresummary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytestsessionscoresummary',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_tests.grouptestmarkslibrary'),
        ),
        migrations.AlterField(
            model_name='ccsessionscoresummary',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_tests.combinedgrouptestmarkslibrary'),
        ),
        migrations.AlterField(
            model_name='subtestsessionscoresummary',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_tests.subtestsmarkslibrary'),
        ),
    ]
