# Generated by Django 4.1 on 2024-02-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tests', '0015_alter_categorytestsessionscoresummary_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='easyquestion',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
