# Generated by Django 4.1 on 2024-01-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancecategorysession',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='attendanceccsession',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='attendancesubtest',
            name='institute',
        ),
    ]
