# Generated by Django 4.1 on 2024-02-09 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_combinedtestcategory_description'),
        ('user_profiles', '0005_remove_questionstatistics_easy_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionstatistics',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tests.category'),
        ),
    ]
