# Generated by Django 4.1 on 2024-02-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0006_questionstatistics_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='Please Enter you address', max_length=100),
        ),
    ]
