# Generated by Django 4.1 on 2024-02-18 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_tests', '0009_alter_easyquestion_category_and_more'),
        ('user_profiles', '0008_rename_combinedgrouptestscoreslibrary_combinedgrouptestmarkslibrary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combinedgrouptestmarkslibrary',
            name='category',
        ),
        migrations.RemoveField(
            model_name='grouptestmarkslibrary',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subtestsmarkslibaray',
            name='category',
        ),
        migrations.AddField(
            model_name='combinedgrouptestmarkslibrary',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='group_tests.combinedcategorytestsession'),
        ),
        migrations.AddField(
            model_name='grouptestmarkslibrary',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='group_tests.categorytestsession'),
        ),
        migrations.AddField(
            model_name='subtestsmarkslibaray',
            name='session',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='group_tests.subtestsession'),
        ),
    ]
