# Generated by Django 4.1 on 2024-02-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0010_alter_combinedgrouptestmarkslibrary_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptestmarkslibrary',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='grouptestmarkslibrary',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='grouptestmarkslibrary',
            name='session',
        ),
        migrations.RemoveField(
            model_name='subtestsmarkslibaray',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='subtestsmarkslibaray',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='subtestsmarkslibaray',
            name='session',
        ),
        migrations.DeleteModel(
            name='CombinedGroupTestMarksLibrary',
        ),
        migrations.DeleteModel(
            name='GroupTestMarksLibrary',
        ),
        migrations.DeleteModel(
            name='SubTestsMarksLibaray',
        ),
    ]
