# Generated by Django 4.1 on 2024-01-16 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('easy_test_file', models.FileField(upload_to='media/group_test_files/')),
                ('medium_test_file', models.FileField(upload_to='media/group_test_files/')),
                ('hard_test_file', models.FileField(upload_to='media/group_test_files/')),
                ('has_password', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupTestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Group Test Categories',
            },
        ),
        migrations.CreateModel(
            name='GroupTestCombinedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('associated_categories', models.ManyToManyField(to='group_tests.grouptestcategory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_info', to='group_tests.grouptest')),
            ],
        ),
        migrations.CreateModel(
            name='MediumQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.ForeignKey(blank=True, default='Coding', null=True, on_delete=django.db.models.deletion.CASCADE, to='group_tests.grouptestcategory')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_tests.grouptest')),
            ],
        ),
        migrations.CreateModel(
            name='HardQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.ForeignKey(blank=True, default='Coding', null=True, on_delete=django.db.models.deletion.CASCADE, to='group_tests.grouptestcategory')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_tests.grouptest')),
            ],
        ),
        migrations.CreateModel(
            name='GroupTestPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_info', to='group_tests.grouptestcombinedcategory')),
            ],
        ),
        migrations.AddField(
            model_name='grouptest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_tests.grouptestcategory'),
        ),
        migrations.AddField(
            model_name='grouptest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EasyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.ForeignKey(blank=True, default='Coding', null=True, on_delete=django.db.models.deletion.CASCADE, to='group_tests.grouptestcategory')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_tests.grouptest')),
            ],
        ),
        migrations.CreateModel(
            name='CombinedCategoryTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('has_password', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('combined_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_tests.grouptestcombinedcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CombinedCategorySessionPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_tests.combinedcategorytestsession')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceForMediumQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_tests.mediumquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceForHardQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_tests.hardquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceForEasyQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_tests.easyquestion')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('has_password', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_tests.grouptestcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategorySessionPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_tests.categorytestsession')),
            ],
        ),
    ]
