# Generated by Django 4.1 on 2024-01-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tests', '0002_remove_grouptest_has_password_subtestsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytestsession',
            name='duration',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='combinedcategorytestsession',
            name='duration',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='subtestsession',
            name='duration',
            field=models.IntegerField(default=20),
        ),
    ]
