# Generated by Django 4.1 on 2024-02-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_tests', '0005_rename_title_grouptest_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptest',
            name='easy_test_file',
        ),
        migrations.RemoveField(
            model_name='grouptest',
            name='hard_test_file',
        ),
        migrations.RemoveField(
            model_name='grouptest',
            name='medium_test_file',
        ),
    ]
