# Generated by Django 4.1 on 2024-02-21 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group_tests', '0011_subtestsessionsdata_grouptestsessionsdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTestSessionScoreSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_tests.categorytestsession')),
            ],
        ),
        migrations.CreateModel(
            name='CCSessionScoreSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_tests.combinedcategorytestsession')),
            ],
        ),
        migrations.CreateModel(
            name='SubTestSessionScoreSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_tests.subtestsession')),
            ],
        ),
        migrations.RemoveField(
            model_name='grouptestsessionsdata',
            name='session',
        ),
        migrations.RemoveField(
            model_name='grouptestsessionsdata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subtestsessionsdata',
            name='session',
        ),
        migrations.RemoveField(
            model_name='subtestsessionsdata',
            name='user',
        ),
        migrations.DeleteModel(
            name='CCTestSessionsData',
        ),
        migrations.DeleteModel(
            name='GroupTestSessionsData',
        ),
        migrations.DeleteModel(
            name='SubTestSessionsData',
        ),
    ]
