# Generated by Django 4.1 on 2024-02-08 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profiles', '0003_alter_attendancecategorysession_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easy_count', models.IntegerField(default=10)),
                ('medium_count', models.IntegerField(default=10)),
                ('hard_count', models.IntegerField(default=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
