# Generated by Django 4.1 on 2024-02-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_combinedtestcategory_description'),
        ('user_profiles', '0004_questionstatistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionstatistics',
            name='easy_count',
        ),
        migrations.RemoveField(
            model_name='questionstatistics',
            name='hard_count',
        ),
        migrations.RemoveField(
            model_name='questionstatistics',
            name='medium_count',
        ),
        migrations.AddField(
            model_name='questionstatistics',
            name='easy_count',
            field=models.ManyToManyField(to='tests.easyquestion'),
        ),
        migrations.AddField(
            model_name='questionstatistics',
            name='hard_count',
            field=models.ManyToManyField(to='tests.hardquestion'),
        ),
        migrations.AddField(
            model_name='questionstatistics',
            name='medium_count',
            field=models.ManyToManyField(to='tests.mediumquestion'),
        ),
    ]
