# Generated by Django 4.1 on 2024-02-18 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group_tests', '0009_alter_easyquestion_category_and_more'),
        ('user_profiles', '0007_profile_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CombinedGroupTestScoresLibrary',
            new_name='CombinedGroupTestMarksLibrary',
        ),
        migrations.CreateModel(
            name='SubTestsMarksLibaray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_subtest_test_marks', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_tests.grouptestcombinedcategory')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_subtest_test_marks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
